### ISSUE TITLE
There is a issuse to reproduce the work?

### ISSUE THREAD

**Issue by Tony-Hou** [wayveai/mile#16]
To run below commands:
`bash run/data_collect.sh /home/linjiehou/workspace/personal/rl/carla/CarlaUE4.sh ./carla_dataset/ 2000 lb_data.yaml`
enviroments:  carlar version 0.9.12  other tools is same with environment.yml.

mile/carla_gym/carla_multi_agent_env.py", line 78, in reset
    ev_spawn_locations = self._ev_handler.reset(self._task['ego_vehicles'])
  File "/home/linjiehou/workspace/personal/auto/mile/carla_gym/core/task_actor/ego_vehicle/ego_vehicle_handler.py", line 37, in reset
    blueprint = np.random.choice(self._world.get_blueprint_library().filter(bp_filter))
  File "mtrand.pyx", line 915, in numpy.random.mtrand.RandomState.choice

How to download carla client 0.9.11 version?

**Comment by anthonyhu** [comment]
You have to download CARLA 0.9.11. This work was not tested on CARLA 0.9.12.

It can be downloaded at https://github.com/carla-simulator/carla/releases/tag/0.9.11

**Comment by Tony-Hou** [comment]
How to download carla client 0.9.11 version?
