### ISSUE TITLE
Questions about the latent code

### ISSUE THREAD

**Issue by Yihanhu** [wayveai/mile#19]
Thank you for sharing your excellent work. 

I have a few questions regaring the latent code in Section 5.4.

![image](https://github.com/wayveai/mile/assets/33394567/b22d1fb1-9d48-4eed-8a16-54043f959e4c)

1. You mentioned that your model can model diverse futures in latent space, here you visualise two distinct futures predicted by the model: 1) (top row) driving through the green light, 2) (bottom row) stopping because the model imagines the traffic light turning red. Did you modeled two different scenario by sampled from latent space?
2. Because in your model, you only sample from a high-dimensional unimodal Gaussian distribution, the latent space remains unimodal. Personally, I feel that a traffic intersection with a red light and a green light (as shown in the diagram) represents two distinct modes, and they may correspond to a bimodal distribution in the latent space. I'm curious to know how you handle multimodal situations when modeling the latent space using a unimodal Gaussian distribution like you do. Or would it be better to use multimodel gaussian mixture instead of unimodel gaussian distribution?

Looking forward for your reply, thank you!

**Comment by anthonyhu** [comment]
Hello Yihan! To answer your questions:

1. That's correct, the two futures displayed correspond to two sampled trajectories from the latent space.
2. That's a question I get often, but the way you can think about this is similar to GANs. In GANs, we sample from a unimodal Gaussian distribution, and use a decoder to output multiple modes (corresponding to different images). Likewise here, even though our latent space is Gaussian unimodal, during training it can be shaped in such a way that the decoder decodes those samples to multimodal outputs.

**Comment by Yihanhu** [comment]
Thank you for your reply! If that's the case, can we also consider the probability of the two scenarios (going straight, stopping) occurring in the latent space as the probability of them possibly happening in the future?

**Comment by Yihanhu** [comment]
What I mean is, if the probability of going straight in the latent space is high, then it also implies that there is a higher probability of going straight happening in the future.

**Comment by anthonyhu** [comment]
That's correct

**Comment by Yihanhu** [comment]
Understood, thank you for your explanation!

**Comment by anthonyhu** [comment]
No prob!
