### ISSUE TITLE
Have you tested it in a real environment?

### ISSUE THREAD

**Issue by beyondpzk** [wayveai/mile#20]

**Comment by anthonyhu** [comment]
Yes I did, and you can also do it yourself by following the instructions there: https://github.com/wayveai/mile#-evaluation :)

**Comment by airobotis** [comment]
@anthonyhu

I have some questions for MILE

1. Have you trained the model with actual environmental data and tested it in a real environment? Or did you train the model with the data obtained from CARLA and conduct the vehicle experiment  in a real environment using the sim2real technique?
2. Is MILE mainly used in actual driving environments?

Thanks for your time.

**Comment by anthonyhu** [comment]
If by real environment you mean real-world on-road testing, then the answer is no. MILE was trained and evaluated in a simulated environment: CARLA.
