### ISSUE TITLE
How to increase speed when performing closed-loop validation at Carla

### ISSUE THREAD

**Issue by KevinDu1** [wayveai/mile#26]
Seeing that the code sets the Carla's FPS to 25Hz causes it to take a day to run one round of validation when running evaluate.py, how can I set it up so that the model can be validated faster?

**Comment by anthonyhu** [comment]
According to the CARLA developers, the minimum FPS you can set is 10Hz. For faster evaluation, I set the constant `CARLA_FPS=10` here https://github.com/wayveai/mile/blob/main/mile/constants.py#L4.

If you are evaluating single-frame models, it should work with a pretrained model. But if you're using temporal models, you have to make sure that the model was trained on the correct temporal stride.

**Comment by KevinDu1** [comment]
Thanks！
