### ISSUE TITLE
How to get a video that contains IMAGINING with evaluate.py?

### ISSUE THREAD

**Issue by airobotis** [wayveai/mile#38]
How to get a video that contains IMAGINING with evaluate.py ?
like Predicted scenario 1 (green light) video  on  https://wayve.ai/thinking/learning-a-world-model-and-a-driving-policy/

Do you offer any parameters to record it ?

Thanks a lot.

**Comment by anthonyhu** [comment]
Hello, this is achieved by setting the parameter `is_dreaming=True` in here https://github.com/wayveai/mile/blob/main/mile/models/mile.py#L397. This will ensure the model gets no additional image observation and will need to update its future state from its internal world model.

**Comment by airobotis** [comment]
I appreciate your kind and quick answer  :)

**Comment by airobotis** [comment]
I appreciate your quick and kind response : )
