### ISSUE TITLE
evaluate error

### ISSUE THREAD

**Issue by ljssuifeng** [wayveai/mile#7]
thanks for your work! 
I follow the instructions of the Readme.txt, create the conda environment and download carla14, but when the evaluate step was done, it pops AssertionError() like this: 
  "  assert mdl is not None
    AssertionError "

could you give me some suggestion to resolve the error.

when the evaluate task is running, need vehicle actors spawn to the map manually?

**Comment by anthonyhu** [comment]
The code is only compatible with [Carla 0.9.11 ](https://github.com/carla-simulator/carla/releases/tag/0.9.11)for now (and not carla 0.9.14) :)
