### ISSUE TITLE
Clarification regarding RGB reconstruction loss

### ISSUE THREAD

**Issue by truncs** [wayveai/mile#9]
It seems like the MILE paper mentions that the RGB reconstruction loss is used but the config in the code has it disabled with the comment that the parameter is only used for other models. Specifically the following

```
_C.EVAL.RGB_SUPERVISION = False
```
Are the results with or without the RGB reconstruction loss?

**Comment by anthonyhu** [comment]
Hi,

We found the supervision from bird's-eye view semantic segmentation to be sufficient and did not need to include supervision from RGB reconstruction. This notably allows GPU memory saving.

**Comment by truncs** [comment]
Thank you for clarifying!

**Comment by anthonyhu** [comment]
No prob!
